# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.enableR8.fullMode=false

# Optional keystore properties for assembleRelease
# RELEASE_STORE_FILE=my-release-key.jks
# RELEASE_STORE_PASSWORD=password
# RELEASE_KEY_ALIAS=my-key-alias
# RELEASE_KEY_PASSWORD=password
